from TestHelperSuperClass import testHelperSuperClass
from unittest.mock import patch
import passwordmanpro_cli
import datetime
import json

appObj = passwordmanpro_cli.AppObjClass()

envNoKey = dict()
envNoKey['PASSMANCLI_URL'] = 'TESTINGURL'
env = dict(envNoKey)
env['PASSMANCLI_AUTHTOKEN'] = 'TESTINGURL'

resourseResponseRAW = '{"operation":{"name":"GET RESOURCES","result":{"status":"Success","message":"Resources fetched successfully"},"totalRows":2,"Details":[{"RESOURCE DESCRIPTION":"Expermental server","RESOURCE NAME":"soadevteamserver-konga","RESOURCE ID":"170741","RESOURCE TYPE":"Linux","NOOFACCOUNTS":"1"},{"RESOURCE DESCRIPTION":"Expermental server","RESOURCE NAME":"soadevteamserver-portainer","RESOURCE ID":"171317","RESOURCE TYPE":"Linux","NOOFACCOUNTS":"1"}]}}'
resourseResponse = json.loads(resourseResponseRAW)

accountsResponseRAW = '{"operation":{"name":"GET RESOURCE ACCOUNTLIST","result":{"status":"Success","message":"Resource details with account list fetched successfully"},"Details":{"RESOURCE ID":"170741","RESOURCE NAME":"soadevteamserver-konga","RESOURCE DESCRIPTION":"Expermental server","RESOURCE TYPE":"Linux","DNS NAME":"ic-soadevteam.cc.ic.ac.uk","PASSWORD POLICY":"Default IC Password Policy","DEPARTMENT":"soadev team","LOCATION":"","RESOURCE URL":"http://ic-soadevteam.cc.ic.ac.uk/konga","RESOURCE OWNER":"IC\\rjmetcal","CUSTOM FIELD":[{"CUSTOMFIELDVALUE":"","CUSTOMFIELDTYPE":"Password","CUSTOMFIELDLABEL":"Initial Screen Logon","CUSTOMFIELDCOLUMNNAME":"COLUMN_SCHAR1"},{"CUSTOMFIELDVALUE":"Development","CUSTOMFIELDTYPE":"Character","CUSTOMFIELDLABEL":"Usage","CUSTOMFIELDCOLUMNNAME":"COLUMN_CHAR1"}],"ACCOUNT LIST":[{"ISFAVPASS":"false","ACCOUNT NAME":"kongaadmin","PASSWDID":"244321","IS_TICKETID_REQD_MANDATORY":"false","ISREASONREQUIRED":"false","AUTOLOGONLIST":["Putty","SSH"],"PASSWORD STATUS":"****","IS_TICKETID_REQD":"false","ACCOUNT ID":"244321","AUTOLOGONSTATUS":"User is not allowed to automatically logging in to remote systems in mobile","IS_TICKETID_REQD_ACW":"false"}]}}}'
accountsResponse = json.loads(accountsResponseRAW)

passwordResponseRAW = '{"operation":{"name":"GET PASSWORD","result":{"status":"Success","message":"Password fetched successfully"},"Details":{"PASSWORD":"dummyPasswordForTest"}}}'
passwordResponse = json.loads(passwordResponseRAW)

resourseResponseNoResoursesRAW = '{"operation":{"name":"GET RESOURCES","result":{"status":"Success","message":"Resources fetched successfully"},"totalRows":0}}'
resourseResponseNoResourses = json.loads(resourseResponseNoResoursesRAW)

class test_AppObj(testHelperSuperClass):
  @patch('passwordmanpro_cli.AppObjClass._callGetResourses')
  @patch('passwordmanpro_cli.AppObjClass._callGetAccounts')
  @patch('passwordmanpro_cli.AppObjClass._callGetPassword')
  def test_JavaPropsNoFilter(self, _callGetPasswordResponse, _callGetAccountsResponse, _callGetResoursesResponse):
    _callGetResoursesResponse.side_effect  = [
      { 'responseCode': 200, 'response': resourseResponse},
    ]
    _callGetAccountsResponse.side_effect  = [
      { 'responseCode': 200, 'response': accountsResponse},
      { 'responseCode': 200, 'response': accountsResponse}
    ]
    _callGetPasswordResponse.side_effect  = [
      { 'responseCode': 200, 'response': passwordResponse},
      { 'responseCode': 200, 'response': passwordResponse}
    ]
    testTime = datetime.datetime(2016,1,5,14,2,59,0,None)
    returnedValue = appObj.runWithTime(env, ['passwordmanpro_cli', 'javaprops'], testTime)
    self.assertEqual(appObj.url,envNoKey['PASSMANCLI_URL'])
    self.assertEqual(appObj.authtoken,env['PASSMANCLI_AUTHTOKEN'])
    self.assertEqual(appObj.filterToUse,None,msg='Filter should be none')
    
    expectedResult = "# Java properties file generated by https://github.com/rmetcalf9/PasswordManPro_CLI"
    expectedResult = expectedResult + "\n" + "# on 2016-01-05 14:02:59"
    expectedResult = expectedResult + "\n" + ""
    expectedResult = expectedResult + "\n" + ""
    expectedResult = expectedResult + "\n" + "soadevteamserver-konga.username = kongaadmin"
    expectedResult = expectedResult + "\n" + "soadevteamserver-konga.password = dummyPasswordForTest"
    expectedResult = expectedResult + "\n" + ""
    expectedResult = expectedResult + "\n" + "soadevteamserver-portainer.username = kongaadmin"
    expectedResult = expectedResult + "\n" + "soadevteamserver-portainer.password = dummyPasswordForTest"
    expectedResult = expectedResult + "\n" + ""
    expectedResult = expectedResult + "\n" + "# End of file"
    expectedResult = expectedResult + "\n\n" + ""
    
    self.maxDiff = None
    
    self.assertEqual(returnedValue, expectedResult, msg='Incorrect output')

  @patch('passwordmanpro_cli.AppObjClass._callGetResourses')
  @patch('passwordmanpro_cli.AppObjClass._callGetAccounts')
  @patch('passwordmanpro_cli.AppObjClass._callGetPassword')
  def test_JavaPropsSimpleFilter(self, _callGetPasswordResponse, _callGetAccountsResponse, _callGetResoursesResponse):
    _callGetResoursesResponse.side_effect  = [
      { 'responseCode': 200, 'response': resourseResponse},
    ]
    _callGetAccountsResponse.side_effect  = [
      { 'responseCode': 200, 'response': accountsResponse},
      { 'responseCode': 200, 'response': accountsResponse}
    ]
    _callGetPasswordResponse.side_effect  = [
      { 'responseCode': 200, 'response': passwordResponse},
      { 'responseCode': 200, 'response': passwordResponse}
    ]
    testTime = datetime.datetime(2016,1,5,14,2,59,0,None)
    returnedValue = appObj.runWithTime(env, ['passwordmanpro_cli', 'javaprops', 'konga'], testTime)
    self.assertEqual(appObj.url,envNoKey['PASSMANCLI_URL'])
    self.assertEqual(appObj.authtoken,env['PASSMANCLI_AUTHTOKEN'])
    self.assertEqual(appObj.filterToUse,'konga')
    
    expectedResult = "# Java properties file generated by https://github.com/rmetcalf9/PasswordManPro_CLI"
    expectedResult = expectedResult + "\n" + "# on 2016-01-05 14:02:59"
    expectedResult = expectedResult + "\n" + ""
    expectedResult = expectedResult + "\n" + ""
    expectedResult = expectedResult + "\n" + "soadevteamserver-konga.username = kongaadmin"
    expectedResult = expectedResult + "\n" + "soadevteamserver-konga.password = dummyPasswordForTest"
    expectedResult = expectedResult + "\n" + ""
    expectedResult = expectedResult + "\n" + "# End of file"
    expectedResult = expectedResult + "\n\n" + ""
    
    self.maxDiff = None
    
    self.assertEqual(returnedValue, expectedResult, msg='Incorrect output')

  def test_JavaPropsSimpleFilterTooMangArguments(self):
    with self.assertRaises(Exception) as context:
      returnedValue = appObj.run(env, ['passwordmanpro_cli', 'javaprops', 'konga', 'ExtraArg'])
    self.checkGotRightException(context,passwordmanpro_cli.badArgumentsException)

  @patch('passwordmanpro_cli.AppObjClass._callGetResourses')
  def test_JavaPropsZeroSharedReosurses(self, _callGetResoursesResponse):
    _callGetResoursesResponse.side_effect  = [
      { 'responseCode': 200, 'response': resourseResponseNoResourses},
    ]
    testTime = datetime.datetime(2016,1,5,14,2,59,0,None)
    returnedValue = appObj.runWithTime(env, ['passwordmanpro_cli', 'javaprops'], testTime)
    self.assertEqual(appObj.url,envNoKey['PASSMANCLI_URL'])
    self.assertEqual(appObj.authtoken,env['PASSMANCLI_AUTHTOKEN'])
    self.assertEqual(appObj.filterToUse,None,msg='Filter should be none')
    
    expectedResult = "# Java properties file generated by https://github.com/rmetcalf9/PasswordManPro_CLI"
    expectedResult = expectedResult + "\n" + "# on 2016-01-05 14:02:59"
    expectedResult = expectedResult + "\n" + ""
    expectedResult = expectedResult + "\n" + ""
    expectedResult = expectedResult + "\n" + "# End of file"
    expectedResult = expectedResult + "\n\n" + ""
    
    self.maxDiff = None
    
    self.assertEqual(returnedValue, expectedResult, msg='Incorrect output')

